# MySQL 설정

server:
  address: localhost
  port: 8080

into-book:
  api:
    key: ttbjmj25885471405001

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/intobook?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&useSSL=true
    username: root
    password: root

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

# createDatabaseIfNotExist: 데이터베이스가 존재하지 않으면 자동으로 생성
# useUnicode: 유니코드 사용 여부 설정
# characterEncoding: 문자열 인코딩 종류 설정
# characterSetResult: 결과값의 인코딩 종류 설정
# useSSL: SSL 사용여부 설정

# spring.jpa.properties.hibernate.show_sql : 하이버네이트가 실행한 모든 SQL문을 콘솔로 출력
# spring.jpa.properties.hibernate.format_sql : SQL문을 가독성 있게 표현

swagger:
  project:
    base-package: com.reboot.intobook.*